# Generated by Django 2.2.4 on 2019-09-01 17:18

from django.db import migrations

from common.enums import Groups


def form_groups(apps, _schema_editor):
    """
    Migration
    :param apps:
    :param _schema_editor:
    :return:
    """
    _Group = apps.get_model('auth', 'Group')
    for group in Groups:
        _Group.objects.create(name=group.value)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(form_groups),
    ]
